In [25]:
import numpy as np
import operator

In [47]:
filename = 'user-shows_copy.txt'
f = open(filename, 'r')

# compute P
p = np.zeros((3, 3))
r = np.zeros((3, 5))
i = 0
for user in f:
    ui = list(int(u) for u in user.strip().split())
    r[i] = ui
    p[i][i] = np.sum(ui)
    i = i + 1
print(r)

[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 1.]]


In [31]:
users = [0] * 5

In [32]:
f = open(filename, 'r')
for user in f:
    ui = list(int(u) for u in user.strip().split())
    users = np.add(users, ui)
print(users)

[2 2 1 1 2]


In [33]:
q = np.zeros((5, 5))
for num in range(len(users)):
    q[num][num] = users[num]

In [40]:
q_half = q
for i in range(len(users)):
    if q_half[i][i] != 0:
        q_half[i][i] = 1/np.sqrt(q_half[i][i])

In [49]:
tau_1 = np.dot(r, q_half)
tau_2 = np.dot(tau_1, np.transpose(r))
tau_3 = np.dot(tau_2, r)
tau_show = np.dot(tau_3, q_half)

In [50]:
tau_show

array([[5.92443352, 5.92443352, 4.52268925, 4.52268925, 5.92443352],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [4.24264069, 4.24264069, 2.52268925, 2.52268925, 4.24264069]])

In [55]:
s_show = tau_show[:, 0:4]

In [56]:
s_show

array([[5.92443352, 5.92443352, 4.52268925, 4.52268925],
       [0.        , 0.        , 0.        , 0.        ],
       [4.24264069, 4.24264069, 2.52268925, 2.52268925]])

In [72]:
s_alex=s_show[2]
alex = {}
for i in range(len(s_alex)):
    alex[i] = s_alex[i]
alex

{0: 4.242640687119286,
 1: 4.242640687119286,
 2: 2.5226892457611436,
 3: 2.5226892457611436}

In [96]:
recommend_alex = dict(sorted(alex.items(), key=lambda x: (x[1], x[0]))[0:3])

In [97]:
recommend_alex

{2: 2.5226892457611436, 3: 2.5226892457611436, 0: 4.242640687119286}

In [98]:
showfile = 'shows_copy.txt'
f_show = open(showfile, 'r')
showi = []
for show in f_show:
    showi.append(show)

In [99]:
recommend_alex

{2: 2.5226892457611436, 3: 2.5226892457611436, 0: 4.242640687119286}

In [103]:
print('Top 4 Recommendation for Alex: ') 
for show,score in recommend_alex.items():
    print(showi[show], score)

Top 4 Recommendation for Alex: 
"Dancing with the Stars"
 2.5226892457611436
"The Colbert Report"
 2.5226892457611436
"The Situation Room with Wolf Blitzer"
 4.242640687119286
